### ISSUE TITLE
Error working with Freshdesk Tap

### ISSUE THREAD

**Issue by dtaylor072** [statsbotco/target-postgres#1]
Hi, when attempting to use Freshdesk as a singer tap with this postgres target, db_sync.py throws an error in 'flatten_schema' because value v does not always have an element named 'type', because it can be an array. The exception occurs when value v contains the value 'anyOf', as is such in an example of a value v here:

{'anyOf': [{'type': 'array', 'items': {'type': 'string'}}, {'type': 'null'}]}

This causes db_sync.py to throw the following error:

line 58, in flatten_schema
if 'object' in v['type']:
KeyError: 'type'

I am able to get around this simply by checking first for the existence of 'type' in v, then handling v properly as an array if it is of type array. Thanks

**Comment by paveltiunov** [comment]
Hey @dtaylor072 ! 
Could you please try to install it from git repository? I guess it should be fixed already. We'll bump version and update pip soon.

**Comment by dtaylor072** [comment]
I have done this, and still the same error. The 'type' is still not
contained in elements that are arrays.


David

**Comment by paveltiunov** [comment]
@dtaylor072 Could you please send error message with stack trace for this error?
